# Generated by Django 3.0.3 on 2020-02-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whidami', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='title',
            field=models.TextField(default='Title'),
        ),
    ]
