# Generated by Django 3.0.3 on 2020-02-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whidami', '0002_filemodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='title',
        ),
    ]
